---
name: Blank issue (intended only for Halo engineers)
about: Create a new issue from scratch
title: ''
assignees: ''
type: Feature request
---

(If you’re not a Halo Engineer, please select the Bug Report or Feature Request template instead.)
